Modified augments to be NBT based
InnovativeOnlineIndustries/Titanium pull request #70
Opened 2020-07-13 15:37 UTC by Buuz135

2020-07-13 15:42 UTC, SkySomDynata requested changes

2020-07-13 15:42 UTC, SkySomDynata commented on src/main/java/com/hrznstudio/titanium/block/tile/MachineTile.java
> +            .setInputFilter((stack, integer) -> new AugmentWrapper(stack).isAugment() && canAcceptAugment(stack)));
Doing the same check twice?

2020-07-13 15:42 UTC, SkySomDynata commented on src/main/java/com/hrznstudio/titanium/block/tile/MachineTile.java
> +        return getItemStackAugments().stream().map(AugmentWrapper::new).filter(AugmentWrapper::isAugment).filter(augmentController -> augmentController.hasType(filter)).collect(Collectors.toList());
Seems like a lot of object creations just to get rid of things?

2020-07-13 15:55 UTC, SkySomDynata approved these changes

2020-07-14 02:58 UTC, SkySom approved these changes

2020-07-15 11:36 UTC, merged